# Configuración del Servidor
server.port=5000

# CoinMarketCap Config
coinmarketcap.api.key=dc658feb-6fda-42cd-8ae4-ab4d4d2621f6
coinmarketcap.base.url=https://pro-api.coinmarketcap.com

# Habilitar logs para debugging (opcional)
logging.level.org.springframework.web=INFO

server.servlet.context-path=/api/v1
springdoc.swagger-ui.path=/docs