# Usa el puerto de Render o 5000 por defecto
server.port=${PORT:5000}

# Leer la clave desde las variables de entorno de Render
coinmarketcap.api.key=${COINMARKETCAP_API_KEY}
coinmarketcap.base.url=https://pro-api.coinmarketcap.com

# Logs y Path
logging.level.org.springframework.web=INFO
server.servlet.context-path=/api/v1
springdoc.swagger-ui.path=/docs